### ISSUE TITLE
模板配置无效

### ISSUE THREAD

**Issue by hanjunchen** [mustfun/mybatis-lite#41]
修改了模板，但是生成的代码还是按初始模板生成的

**Comment by hrj5032188** [comment]
我也遇到了这种情况
修改了mapper模板.vm之后 重新生成.xml文件
还是原来的xml
并没有根据我修改的模板去生成 
IDEA版本2019.1.3(Ultimate Edition)
![image](https://user-images.githubusercontent.com/28888068/61198725-d3b86000-a70d-11e9-9c0a-ccde5897fb62.png)
插件版本 v1.0.11

**Comment by hrj5032188** [comment]
我是不是搞错了?
这里是idea插件 MyBatis Lite吗?
为什么release里最新版才1.0.7
我......

**Comment by mustfun** [comment]
没搞错，这里的release没有维护了，这个bug之前有人反馈过，我倒是没碰到，我下个新版本的看一下吧

**Comment by mustfun** [comment]
欢迎体验新版，新版改进和增加了很多内容，改bug已于历史版本修复
