### ISSUE TITLE
针对模板，选择性的生成部分代码

### ISSUE THREAD

**Issue by nmyphp** [mustfun/mybatis-lite#48]
![image](https://user-images.githubusercontent.com/14543404/71052053-34e4d380-2185-11ea-87e4-139bcde9090f.png)

能否加一个单选框，在dao\mapper\service\controller选择性的生成，比如只生成dao和mapper

**Comment by mustfun** [comment]
点击连接之后不是有单选框，可以选择性生成吗？

**Comment by nmyphp** [comment]
好的，我看到了，要得就是这个效果
![image](https://user-images.githubusercontent.com/14543404/71052759-5a72dc80-2187-11ea-8b4f-6ba4371ae4ae.png)

**Comment by nmyphp** [comment]
好的，我看到了，要得就是这个效果
