### ISSUE TITLE
代码生成BUG

### ISSUE THREAD

**Issue by LeeSunGen** [mustfun/mybatis-lite#50]
1.没法默认保存修改数据库连接信息，只记住第一次的连接IP，每次都得手动改
2.选择各层的路径位置，若选择某路径下没有文件，会出现Mapper.xml里命名空间 有null怕拼成
3.选择存放目录，每次默认目录不对，都需要调整
上面的问题，不知道作者有没有遇到，还是免费版的有这问题

**Comment by mustfun** [comment]
1、有这个问题，可以改
2、出现过，找不到PO或者DAO文件路径
3、这个找默认目录，规则是依据项目中有po /bo / service/controller这种文件夹路径去找的，如果没有这种文件夹就找不到啦
感谢反馈，1、2 一定修复

**Comment by LeeSunGen** [comment]
很棒的工具，感谢作者分享，期待新版本

**Comment by mustfun** [comment]
1 - 2在最新版中已经全部修复，且第3点增加记住目录功能，更灵活，欢迎体验最新版

**Comment by LeeSunGen** [comment]
666,更新了



在 2020-02-29 15:00:21，"mustfun" <notifications@github.com> 写道：

1 - 2在最新版中已经全部修复，且第3点增加记住目录功能，更灵活，欢迎体验最新版
