### ISSUE TITLE
Mapper.java 和 Mapper.xml文件异常报错问题

### ISSUE THREAD

**Issue by 811105717** [mustfun/mybatis-lite#52]
插件版本： 1.1.2
IDEA版本： 2019.3.3 （Build #IU193.6494.35）
操作系统： windows 10
问题描述： 当mybatis配置了实体类名简写（type-aliases-package）后 所有的实体类报无法找到的错误
并且默认允许简写类名的类也报同样的错误，例如String 、Integer等

![image](https://user-images.githubusercontent.com/35412811/75602483-9cfa5300-5b00-11ea-8c57-185dd3730de9.png)

![image](https://user-images.githubusercontent.com/35412811/75602489-b8655e00-5b00-11ea-813d-2b32f347c919.png)

**Comment by mustfun** [comment]
请问一下是使用注解的方式还是使用xml配置的方式起的别名

**Comment by 811105717** [comment]
> 请问一下是使用注解的方式还是使用xml配置的方式起的别名

您好，我使用配置文件的方式 yml 配置文件
![image](https://user-images.githubusercontent.com/35412811/75602880-40009c00-5b04-11ea-8cb8-7d057f9f7a4a.png)

**Comment by mustfun** [comment]
> > 请问一下是使用注解的方式还是使用xml配置的方式起的别名
> 
> 您好，我使用配置文件的方式 yml 配置文件
> ![image](https://user-images.githubusercontent.com/35412811/75602880-40009c00-5b04-11ea-8cb8-7d057f9f7a4a.png)

好的，这个情况我没有考虑到，这周加兼容并上传，感谢反馈

**Comment by 811105717** [comment]
> > > 请问一下是使用注解的方式还是使用xml配置的方式起的别名
> > 
> > 
> > 您好，我使用配置文件的方式 yml 配置文件
> > ![image](https://user-images.githubusercontent.com/35412811/75602880-40009c00-5b04-11ea-8cb8-7d057f9f7a4a.png)
> 
> 好的，这个情况我没有考虑到，这周加兼容并上传，感谢反馈

好的 感谢 支持你!

**Comment by 811105717** [comment]
> > > 请问一下是使用注解的方式还是使用xml配置的方式起的别名
> > 
> > 
> > 您好，我使用配置文件的方式 yml 配置文件
> > ![image](https://user-images.githubusercontent.com/35412811/75602880-40009c00-5b04-11ea-8cb8-7d057f9f7a4a.png)
> 
> 好的，这个情况我没有考虑到，这周加兼容并上传，感谢反馈

您好，刚更新了插件 发i西安问题貌似还是存在

**Comment by mustfun** [comment]
久等啦，因jetbrains审核较慢，目前已更新V1.1.5版本，已解决该问题，谢谢
ps: 上次的更新是一个小版本更新，不是这个bug修复哦，另外再看下提示是否正常，谢谢
