### ISSUE TITLE
@AutoWired 错误的提示

### ISSUE THREAD

**Issue by bpzhang** [mustfun/mybatis-lite#53]
![image](https://user-images.githubusercontent.com/1734396/75641276-a3a8d780-5c72-11ea-93fb-4ae183aba46d.png)

**Comment by mustfun** [comment]
谢谢反馈，本周修复

**Comment by mustfun** [comment]
久等啦，因jetbrains审核较慢，目前已更新V1.1.5版本，已解决该问题，谢谢
