### ISSUE TITLE
selectKey的错误提示

### ISSUE THREAD

**Issue by bpzhang** [mustfun/mybatis-lite#57]
在insert内加入selectKey标签的时候 会提示加入id熟悉 并标红
selectKey 没有id属性
![image](https://user-images.githubusercontent.com/1734396/77376110-700d2900-6daa-11ea-8b48-aafcb7b1ce09.png)

**Comment by mustfun** [comment]
感谢反馈，目前已经修复，V1.1.7解决这个问题

**Comment by mustfun** [comment]
新版本已发布
