### ISSUE TITLE
打开Generator Code界面时出现空指针异常

### ISSUE THREAD

**Issue by lonelyTravel** [mustfun/mybatis-lite#58]
![image](https://user-images.githubusercontent.com/50568005/80294995-3f515280-87a1-11ea-80dc-4f27d3535801.png)

**Comment by mustfun** [comment]
请问打开的项目是否空项目？ 要存在一个正常的maven或者gradle项目才行哦

**Comment by lonelyTravel** [comment]
> 请问打开的项目是否空项目？ 要存在一个正常的maven或者gradle项目才行哦

是正常的Maven项目，不是空项目，在Idea 2019.1.4和2020均会出现该异常

**Comment by mustfun** [comment]
是win10吗？插件没有找到你的工作目录
临时性的解决办法是： 在代码目录里面建立一个model文件夹即可

**Comment by lonelyTravel** [comment]
> 是win10吗？插件没有找到你的工作目录
> 临时性的解决办法是： 在代码目录里面建立一个model文件夹即可

原来是我的微服务父项目把src目录删除了，好像只要有src就行了，多谢解答 :D

**Comment by mustfun** [comment]
好的，不客气
