### ISSUE TITLE
@Inject @autowire 注解报错，

### ISSUE THREAD

**Issue by yao00jun** [mustfun/mybatis-lite#8]
@Inject
private IUserDao userDao;
貌似原来的mybatis plugin  不会报错，
![snipaste_2018-09-19_00-55-44](https://user-images.githubusercontent.com/2508468/45703519-276a2380-bba7-11e8-8605-f5486e53ea95.png)

**Comment by mustfun** [comment]
本功能已修复，感谢反馈
